### ISSUE TITLE
Exception onLoad() when using MariaDB for userstore

### ISSUE THREAD

**Issue by aljaxus** [AerWyn81/AParkour#6]
Getting the following error when enabling the MYSQL external database.

* The service (mariadb) is reachable as it's used by other plugins, hosted on the same VM.
* The database is clean and just created.
* Plugin working just fine if I disable the database.

```
[21:53:38 ERROR]: Error occurred while enabling AParkour v3.6.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/zaxxer/hikari/pool/HikariPool$PoolInitializationException
        at me.davidml16.aparkour.database.DatabaseHandler.<init>(DatabaseHandler.java:19) ~[original-aparkour-3.6.0.jar:?]
        at me.davidml16.aparkour.Main.onEnable(Main.java:142) ~[original-aparkour-3.6.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Airplane-87]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Airplane-87]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Airplane-87]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:535) ~[patched_1.17.1.jar:git-Airplane-87]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:449) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:725) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:308) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1212) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-87]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:148) ~[patched_1.17.1.jar:git-Airplane-87]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[patched_1.17.1.jar:git-Airplane-87]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
```

**Comment by AerWyn81** [comment]
Added in [#7886c31](https://github.com/AerWyn81/AParkour/commit/7886c31bc5f1fe3c967c1d54845b014d7ddc08ea).
Warning, the plugin was not intended to connect MariaDB, I added it without testing more than the connection.

The configuration has changed : 
![Image](https://i.imgur.com/pkNEOog.png)

Try it now, and told me if everything is working as expected!
